# PubkeyAcceptedKeyTypes
#   Specifies the key types that will be accepted for public key
#   authentication as a list of comma-separated patterns.  Alter‐
#   nately if the specified list begins with a ‘+’ character, then
#   the specified key types will be appended to the default set
#   instead of replacing them.  If the specified list begins with a
#   ‘-’ character, then the specified key types (including wild‐
#   cards) will be removed from the default set instead of replac‐
#   ing them.  If the specified list begins with a ‘^’ character,
#   then the specified key types will be placed at the head of the
#   default set.  The default for this option is:
#
#     ecdsa-sha2-nistp256-cert-v01@openssh.com,
#     ecdsa-sha2-nistp384-cert-v01@openssh.com,
#     ecdsa-sha2-nistp521-cert-v01@openssh.com,
#     sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,
#     ssh-ed25519-cert-v01@openssh.com,
#     sk-ssh-ed25519-cert-v01@openssh.com,
#     rsa-sha2-512-cert-v01@openssh.com,
#     rsa-sha2-256-cert-v01@openssh.com,
#     ssh-rsa-cert-v01@openssh.com,
#     ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,
#     sk-ecdsa-sha2-nistp256@openssh.com,
#     ssh-ed25519,sk-ssh-ed25519@openssh.com,
#     rsa-sha2-512,rsa-sha2-256,ssh-rsa
#
#   The list of available key types may also be obtained using "ssh
#   -Q PubkeyAcceptedKeyTypes".
#
PubkeyAcceptedKeyTypes +ssh-dss

