---
- name: install backuppc client packages (apt)
  apt:
    name: "{{ backuppc_client_packages }}"
    state: "present"
    install_recommends: false
    force_apt_get: yes
  tags: backuppc

# Configuration specific to Ubuntu (but not Debian)
#
- name: check if ansible_distribution is Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: backuppc

- name: accept ssh-dss key types
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^PubkeyAcceptedKeyTypes(.*)$"
    line: "PubkeyAcceptedKeyTypes +ssh-dss"
    validate: "sshd -T -f %s"
  when:
    - ansible_distribution != 'Ubuntu'
    - ansible_lsb.major_release|int >= 10
  notify:
    - restart sshd
  tags: backuppc

# Leave this task, I'm guessing we will need it when the backuppc
# server has an OS dist-upgrade
#
# - name: remove ssh-dss key types
#   lineinfile:
#     dest: /etc/ssh/sshd_config
#     state: absent
#     regexp: "^PubkeyAcceptedKeyTypes(.*)$"
#     validate: "sshd -T -f %s"
#   when:
#     - ansible_distribution != 'Ubuntu'
#     - ansible_lsb.major_release|int >= 10
#   notify:
#     - reload sshd
#   tags: backuppc

# Debian release 10 and newer have /etc/sudoer.d/
#
- name: add backuppc user to sudoers.d
  copy:
    content: |
      {{ item.username }} ALL=NOPASSWD:/usr/bin/rsync

    dest: "/etc/sudoers.d/{{ item.username }}"
    mode: "0440"
  with_items:
    - "{{ backuppc_client }}"
  when:
    - ansible_distribution != 'Ubuntu'
    - ansible_lsb.major_release|int >= 10
  tags: backuppc

- name: copy MySQL dump script
  copy:
    src: dump_mysql.sh
    dest: "{{ mysql_dump_script }}"
    mode: "0750"
  when:
    - mysql_dump_script is defined
  tags: backuppc

- name: create /root/.config
  file:
    path: /root/.config/
    state: directory
    owner: root
    group: root
    mode: 0750
  when:
    - mysql_dump_script is defined
  tags: backuppc

- name: touch dumpdb.sh.config
  file:
    path: /root/.config/dumpdb.sh.config
    state: touch
    owner: root
    group: root
    mode: 0640
  when:
    - mysql_dump_script is defined
  tags: backuppc
