---
- name: Install backuppc client packages (apt)
  ansible.builtin.apt:
    name: "{{ backuppc_client_packages }}"
    state: "present"
    install_recommends: false
    force_apt_get: true
  tags: backuppc

# Configuration specific to Ubuntu (but not Debian)
#
- name: Check if ansible_distribution is Ubuntu
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
  tags: backuppc

- name: Dump mysql databases
  ansible.builtin.include_tasks: mysql_dump.yml
  when:
    - mysql_dump_script is defined
  tags: backuppc

- name: Dump postgres databases
  ansible.builtin.include_tasks: postgres_dump.yml
  when:
    - postgres_dump_script is defined
  tags: backuppc

- name: Debug common_library
  ansible.builtin.debug:
    msg: "common_library: {{ common_library }}"
  tags: backuppc_client

- name: Configure monolith /etc/sudoers file
  ansible.builtin.include_tasks: monolithic_sudoers.yml
  when:
    - ansible_lsb.major_release|int < 20
  tags: backuppc_client

- name: Configure /etc/sudoers.d
  ansible.builtin.include_tasks: sudoers_d.yml
  when:
    - ansible_lsb.major_release|int >= 20
  tags: backuppc_client

# Leave this task, I'm guessing we will need it when the backuppc
# server has an OS dist-upgrade
#
# - name: Remove ssh-dss key types
#   lineinfile:
#     dest: /etc/ssh/sshd_config
#     state: absent
#     regexp: "^PubkeyAcceptedKeyTypes(.*)$"
#     validate: "sshd -T -f %s"
#   when:
#     - ansible_distribution != 'Ubuntu'
#     - ansible_lsb.major_release|int >= 10
#   notify:
#     - Reload sshd
#   tags: backuppc
