---
- name: Run ssh-keyscan (IP addresses)
  ansible.builtin.shell: ssh-keyscan -p "{{ ansible_ssh_port | default(22) }}" -H "{{ ansible_ssh_host }}" >> /var/lib/backuppc/.ssh/known_hosts
  remote_user: "{{ backuppc_client_known_hosts_remote_user }}"
  delegate_to: "{{ backuppc_client_known_hosts_server }}"
  throttle: 1
  when: ansible_ssh_host | ansible.utils.ipaddr
  changed_when: true
  tags: backuppc_client

- name: Run ssh-keyscan (hostname)
  ansible.builtin.shell: ssh-keyscan -p "{{ ansible_ssh_port | default(22) }}" -H "{{ inventory_hostname }}" >> /var/lib/backuppc/.ssh/known_hosts
  remote_user: "{{ backuppc_client_known_hosts_remote_user }}"
  delegate_to: "{{ backuppc_client_known_hosts_server }}"
  throttle: 1
  when: not (ansible_ssh_host | ansible.utils.ipaddr)
  changed_when: true
  tags: backuppc_client

- name: Set permissions
  ansible.builtin.file:
    path: /var/lib/backuppc/.ssh/known_hosts
    owner: "{{ backuppc_client_known_hosts_owner }}"
    group: "{{ backuppc_client_known_hosts_group }}"
    mode: "0600"
  remote_user: "{{ backuppc_client_known_hosts_remote_user }}"
  delegate_to: "{{ backuppc_client_known_hosts_server }}"
  tags: backuppc_client
