---
# tasks file for roles/backuppc-client/tasks/main.yml

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: create backuppc users
  user: >
    name="{{ backuppc_client_user }}"
    shell="/bin/bash"
    createhome="yes"
    state="present"
    home="{{ backuppc_client_home }}"
    comment="{{ backuppc_client_comment }}"
  tags: backuppc
  
- name: lock backuppc user account
  command: "/usr/bin/passwd -l {{ backuppc_client_user }}"
  register: result
  failed_when: >
      result.rc != 0
  changed_when:
      result.rc == 0 and ("Gonna always change" in result.stderr)
  tags: backuppc
  
- name: set up authorized_keys
  authorized_key: >
    user="{{ backuppc_client_user }}"
    state="present"
    key_options="{{ backuppc_client_key_options }}"
    key="{{ backuppc_client_authorized_keys|b64decode }}"
    manage_dir="yes"
  tags: backuppc
  
- name: copy sudoers file for safety
  command: "/bin/cp -f /etc/sudoers /etc/sudoers.tmp"
  register: result
  failed_when: >
      result.rc != 0
  changed_when:
      result.rc == 0 and ("Gonna always change" in result.stderr)
  tags: backuppc
  
- name: add backuppc user to sudoers
  lineinfile: >
      dest="/etc/sudoers.tmp" 
      state="present"
      regexp="^rsyncbackup" 
      line="rsyncbackup ALL=NOPASSWD:/usr/bin/rsync"
  tags: backuppc

- name: comment out Default requiretty in sudoers
  lineinfile: >
    dest="/etc/sudoers.tmp"
    state="present" 
    backrefs="yes"
    regexp="^Defaults(\s)+requiretty$"
    line="#Defaults    requiretty"
  tags: backuppc
  
- name: final sudoers file check
  shell: "/usr/sbin/visudo -q -c -f /etc/sudoers.tmp && /bin/cp -f /etc/sudoers.tmp /etc/sudoers"
  register: result
  failed_when: >
      result.rc != 0
  changed_when: >
      result.rc == 0 and ("Gonna always change" in result.stderr)
  tags: backuppc
  