---
- name: Run preflight assertions
  ansible.builtin.include_tasks: preflight.yml
  tags: always

- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution_release'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "default.yml"
      paths:
        - "vars"
  tags: backuppc_client

- name: Import tasks debian.yml
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags: backuppc_client

- name: Import tasks ubuntu.yml
  ansible.builtin.import_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
  tags: backuppc_client

- name: Import tasks redhat.yml
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'
  tags: backuppc_client

# Tasks after this comment (are hopefully) common to a linux bases operating
# systems?
#
- name: Delete old backuppc users
  ansible.builtin.user:
    name: "{{ backuppc_client_item.username }}"
    state: "absent"
    remove: true
  loop: "{{ deprecated_backuppc_username }}"
  loop_control:
    loop_var: backuppc_client_item
  tags: backuppc_client

# Look in group_vars and host_vars for default value for {{ backuppc_client }}
#
- name: Create backuppc user
  ansible.builtin.user:
    name: "{{ backuppc_client_item.username }}"
    shell: "{{ backuppc_client_item.shell }}"
    createhome: true
    state: "present"
    home: "{{ backuppc_client_item.home }}"
    comment: "{{ backuppc_client_item.comment }}"
    password: "*"
    password_lock: true
    update_password: always
  loop: "{{ backuppc_client }}"
  loop_control:
    loop_var: backuppc_client_item
  no_log: true
  changed_when: false
  notify: known_hosts
  tags: backuppc_client

- name: Include tasks ssh_keys.yml
  ansible.builtin.include_tasks: ssh_keys.yml
  tags: backuppc_client

- name: Include tasks known_hosts.yml
  ansible.builtin.include_tasks: known_hosts.yml
  when: backuppc_ssh_key_scan is defined
  tags: backuppc_client
