---
# tasks file for roles/backuppc-client

#- import_tasks: redhat.yml
#  when: ansible_os_family == 'RedHat'

- name: gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: 
    - backuppc
    - backuppc2
    
- name: personal variables
  include_vars: "{{ lookup('env','HOME') }}/.ansible/{{ role_name }}.yml"
  ignore_errors: yes
  tags: backuppc

- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'

#- import_tasks: suse.yml
#  when: ansible_os_family == 'Suse' or ansible_os_family == 'openSUSE'

- name: delete old backuppc users
  user:
    name: "{{ item.username }}"
    state: "absent"
    remove: "yes"
  with_items:
    - "{{ deprecated_backuppc_username }}"
  tags: backuppc

# look in group_vars and host_vars for default value for {{ backuppc_client }}
#
- name: create backuppc user
  user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
    createhome: "yes"
    state: "present"
    home: "{{ item.home }}"
    comment: "{{ item.comment }}"
    password: "*"
    password_lock: yes
  with_items:
      - "{{ backuppc_client }}"
  tags: backuppc

- debug:
    msg: "{{ item.username }}{{ item.authorized_keys }}"
  with_items:
    - "{{ backuppc_client }}"
  tags: backuppc2

- name: set up backuppc user authorized_keys
  authorized_key:
    user: "{{ item.username }}"
    state: "present"
    key_options: "{{ item.key_options }}"
    key: "{{ item.authorized_keys }}"
    manage_dir: "yes"
  with_items:
      - "{{ backuppc_client }}"
  tags: backuppc

- import_tasks: "../lib/sudo-safety-backup.yml"
  tags: backuppc
    
- name: add backuppc user to sudoers
  lineinfile:
    dest: "/etc/sudoers.tmp"
    state: "present"
    regexp: "^{{ item.username }}"
    line: "{{ item.username }} ALL=NOPASSWD:/usr/bin/rsync"
  with_items:
    - "{{ backuppc_client }}"
  tags: backuppc

- import_tasks: "../lib/sudo-safety-restore.yml"
  tags: backuppc

- import_tasks: "../lib/sudo-safety-backup.yml"
  tags: backuppc

- name: delete old backuppc user from sudoers
  lineinfile:
    dest: "/etc/sudoers.tmp"
    state: "absent"
    regexp: "^{{ item.username }}"
  with_items:
    - "{{ deprecated_backuppc_username }}"
  tags: backuppc  

- import_tasks: "../lib/sudo-safety-restore.yml"
  tags: backuppc  

# Can override the location "{{ known_host_keys_dir }}" 
# default is in defaults/main.yml
#
- name: fetch ssh public keys
  fetch:
    src: "/etc/ssh/{{ item }}"
    dest: "{{ known_host_keys_dir }}/known_host_keys"
  with_items:
      - "{{ ssh_host_pub_keys }}"  
  ignore_errors: yes
  register: ssh_host_keys
  tags: 
    - backuppc
    - backuppc2

- debug:
    msg: "{{ ansible_fqdn }},{{ ansible_default_ipv4.address }} {{ lookup('file', item.dest).split(' ')[0:-1] | join(' ') }}"
  when:
    - item.failed == False
  with_items:
    - "{{ ssh_host_keys.results }}"
  ignore_errors: yes
  tags:
    - backuppc
    - backuppc2

- name: add ssh host key to backuppc known_hosts
  known_hosts:
    path: /etc/ssh/ssh_known_hosts
    name: "{{ ansible_fqdn }}"
    key: "{{ ansible_fqdn }},{{ ansible_default_ipv4.address }} {{ lookup('file', item.dest).split(' ')[0:-1] | join(' ') }}"
    state: present
  when: 
    - backuppc_server_hostname is defined
    - item.failed == False    
  with_items:
    - "{{ ssh_host_keys.results }}"
  delegate_to: "{{ backuppc_server_hostname }}"
  remote_user: ansible
  changed_when: 
    - item.changed == True
  tags: 
    - backuppc
    - backuppc2
