---
- name: Sudo backup
  include_tasks: "{{ common_library }}/sudo-safety-backup.yml"
  tags: backuppc_client

- name: Add backuppc user to sudoers
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers.tmp"
    state: "present"
    regexp: "^{{ backuppc_client_item.username }}"
    line: "{{ backuppc_client_item.username }} ALL=NOPASSWD:/usr/bin/rsync"
  loop: "{{ backuppc_client }}"
  loop_control:
    loop_var: backuppc_client_item
  tags: backuppc_client

- name: Delete old backuppc user from sudoers (monolithic)
  ansible.builtin.lineinfile:
    dest: "/etc/sudoers.tmp"
    state: "absent"
    regexp: "^{{ backuppc_client_item }}"
  loop:
    "{{ deprecated_backuppc_username }}"
  loop_control:
    loop_var: backuppc_client_item
  tags: backuppc_client

- name: Sudo restore
  include_tasks: "{{ common_library }}/sudo-safety-restore.yml"
  tags: backuppc_client

- name: Clean up temp file
  ansible.builtin.file:
    path: "/etc/sudoers.tmp"
    state: "absent"
  changed_when: false
  tags: backuppc_client
