---
# Tasks to handle monolithic sudoers files.
#
- name: copy sudoers file for safety
  command: "cp -f /etc/sudoers /etc/sudoers.tmp"
  register: result
  failed_when: result.rc != 0
  changed_when: False
  tags: backuppc

- name: add backuppc user to sudoers
  lineinfile:
    dest: "/etc/sudoers.tmp"
    state: "present"
    regexp: "^{{ item.username }}"
    line: "{{ item.username }} ALL=NOPASSWD:/usr/bin/rsync"
  with_items:
    - "{{ backuppc_client }}"
  tags: backuppc

- name: final sudoers file check
  shell: "/usr/sbin/visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers"
  register: result
  failed_when: result.rc != 0
  changed_when: False

- name: clean up temp file
  file:
    path: "/etc/sudoers.tmp"
    state: "absent"
  changed_when: False
