---
- name: Install backuppc client packages (dnf)
  ansible.builtin.dnf:
    name: "{{ backuppc_client_packages }}"
    state: "present"
  tags: backuppc_client

- name: RedHat dump mysql databases
  ansible.builtin.include_tasks: mysql_dump.yml
  when:
    - mysql_dump_script is defined
  tags: backuppc_client

- name: RedHat dump postgres databases
  ansible.builtin.include_tasks: postgres_dump.yml
  when:
    - postgres_dump_script is defined
  tags: backuppc_client

- name: Configure /etc/sudoers.d
  ansible.builtin.include_tasks: sudoers_d.yml
  tags: backuppc_client
