---
- name: Install backuppc client packages (yum)
  ansible.builtin.yum:
    name: "{{ backuppc_client_packages }}"
    state: "present"
  tags: backuppc

- name: Debug common_library
  ansible.builtin.debug:
    msg: "common_library: {{ common_library }}"
  tags: backuppc_client

- name: Configure /etc/sudoers.d
  ansible.builtin.include_tasks: sudoers_d.yml
  tags: backuppc_client
