---
- name: Delete old backuppc user from sudoers.d
  ansible.builtin.file:
    path: "/etc/sudoers.d/{{ backuppc_client_item.username }}"
    state: absent
  loop:
    "{{ deprecated_backuppc_username }}"
  loop_control:
    loop_var: backuppc_client_item
  tags: backuppc_client

- name: Add backuppc user (rsync) to sudoers.d    # noqa template-instead-of-copy
  ansible.builtin.copy:
    content: |
      {{ backuppc_client_item.username }} ALL=NOPASSWD:/usr/bin/rsync
      Defaults:{{ backuppc_client_item.username }} !use_pty

    dest: "/etc/sudoers.d/{{ backuppc_client_item.username }}_rsync"
    mode: "0440"
    validate: "visudo -cf %s"
  loop: "{{ backuppc_client }}"
  loop_control:
    loop_var: backuppc_client_item
  tags: backuppc_client

- name: Add backuppc user MySQL dump to sudoers.d   # noqa template-instead-of-copy
  ansible.builtin.copy:
    content: |
      {{ backuppc_client_item.username }} ALL=NOPASSWD:{{ mysql_dump_script }}

    dest: "/etc/sudoers.d/{{ backuppc_client_item.username }}_mysql_dump"
    mode: "0440"
  loop: "{{ backuppc_client }}"
  loop_control:
    loop_var: backuppc_client_item
  when:
    - mysql_dump_script is defined
  tags: backuppc_client

- name: Add backuppc user Postgres dump to sudoers.d    # noqa template-instead-of-copy
  ansible.builtin.copy:
    content: |
      {{ backuppc_client_item.username }} ALL=NOPASSWD:{{ postgres_dump_script }}

    dest: "/etc/sudoers.d/{{ backuppc_client_item.username }}_postgres_dump"
    mode: "0440"
  loop: "{{ backuppc_client }}"
  loop_control:
    loop_var: backuppc_client_item
  when:
    - postgres_dump_script is defined
  tags: backuppc_client
