---
- name: Ubuntu major_release >= 20
  when:
    - ansible_facts['lsb']['major_release'] | int >= 20
  block:
    - name: Ubuntu (>= 20) configure openssh server (ubuntu 20.04+)
      ansible.builtin.template:
        src: etc/ssh/sshd_config.d/PubkeyAcceptedKeyTypes.conf.j2
        dest: /etc/ssh/sshd_config.d/PubkeyAcceptedKeyTypes.conf
        owner: root
        group: root
        mode: "0400"
        validate: "sshd -T -f %s"
      notify:
        - Reload sshd
      tags: backuppc_client

    - name: Ubuntu (>= 20) configure /etc/sudoers.d
      ansible.builtin.include_tasks: sudoers_d.yml
      tags: backuppc_client

- name: Ubuntu unsupported release
  ansible.builtin.debug:
    msg: "Ubuntu {{ ansible_facts['distribution_release'] }} is not supported"
  when:
    - ansible_facts['lsb']['major_release'] | int < 20
