---
- name: reload sshd
  ansible.builtin.service:
    name: ssh
    state: reloaded
  tags: backuippc_client

- name: restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  tags: backuippc_client
