---
- name: Converge
  hosts: all
  become: true

  vars:
    deprecated_backuppc_username: []
    backuppc_client:
      - username: 'rsyncbackup'
        home: '/var/lib/rsyncbackup'
        shell: '/bin/bash'
        comment: 'BackupPC User'
        authorized_keys: []
        key_options: ''

  environment:
    TZ: "America/Chicago"   # Keep tzdata pacakge happy
    DEBIAN_FRONTEND: "noninteractive"

  tasks:
    - name: Include_role backuppc_client
      ansible.builtin.include_role:
        name: "backuppc_client"
