---
- name: Prepare molecule tests
  hosts: all
  become: true

  vars:
    prepare_postfix_relay_packages:
      - dialog
      - less
      - vim-tiny


  environment:
    TZ: "America/Chicago"   # Keep tzdata pacakge happy
    DEBIAN_FRONTEND: "noninteractive"

  pre_tasks:

  roles:

  tasks:
    - name: PREPARE update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
        autoremove: true
        autoclean: true
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: PREPARE helper packages
      apt:
        name: "{{ prepare_postfix_relay_packages }}"
        state: present
        install_recommends: no
        force_apt_get: yes

    - name: PREPARE install openssh server
      apt:
        name: openssh-server
        state: present
        force_apt_get: yes
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: PREPARE start openssh server
      service:
        name: ssh
        state: restarted
      changed_when: false
      when: ansible_os_family == 'Debian'
