---
- name: prepare
  hosts: all
  become: true

  vars:
    prepare_packages:
      - dialog
      - less
      - openssh-server    # needed for testing backuppc ssh keys
      - vim-tiny

  environment:
    TZ: "America/Chicago"    # Keep tzdata pacakge happy
    DEBIAN_FRONTEND: "noninteractive"

  tasks:
    - name: PREPARE install packages
      ansible.builtin.apt:
        name: "{{ prepare_packages }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
        install_recommends: false
        force_apt_get: true
        autoremove: true
        autoclean: true
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: restart sshd
      ansible.builtin.command: /etc/init.d/ssh restart
